name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-13

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        brew install cmake molten-vk fftw vulkan-tools
    - name: Build
      run: |
        mkdir build
        cd build
        cmake -DUSE_FFTW=1 .. 
        make -j4
    - name: Run
      run: |
        ./VkFFT_TestSuite -vkfft 11
        
